# Generated by Django 3.0.7 on 2020-10-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0036_auto_20201001_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNP', 'Необработанный'), ('DLV', 'Доставка'), ('DLD', 'Доставлен')], default='UNP', max_length=3),
        ),
    ]
