# Generated by Django 3.0.7 on 2020-10-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNP', 'Необработанный'), ('DLV', 'Доставка'), ('DLD', 'Доставлен')], default='UNP', max_length=3, verbose_name='статус'),
        ),
    ]
