# Generated by Django 3.0.7 on 2020-10-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20201002_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CSH', 'Наличными'), ('ONL', 'Онлайн')], default='CSH', max_length=3, verbose_name='способ оплаты'),
        ),
    ]
